# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('issuing_institution', models.CharField(max_length=100, verbose_name='Orgão Emissor')),
                ('license_number', models.CharField(blank=True, help_text='Número de licença do certificado', max_length=100, verbose_name='Número de licença')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL do certificado')),
                ('document', models.ImageField(blank=True, null=True, upload_to='documentos', verbose_name='Arquivo do certificado')),
                ('issue_date', models.DateField(blank=True, help_text='Data de emissão do certificado', null=True, verbose_name='Data de emissão')),
                ('has_expired_date', models.BooleanField(default=False, verbose_name='Certificado tem data de expiração?')),
                ('expired_date', models.DateField(blank=True, help_text='Data de expiração do certificado', null=True, verbose_name='Data de expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['title', 'issuing_institution', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('location', models.CharField(help_text='Local que foi adquirido a experiencia ou trabalho', max_length=100, verbose_name='Local')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Termino')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_current_job', models.BooleanField(default=False, verbose_name='É o trabalho atual?')),
                ('event_url', models.URLField(blank=True, help_text='URL do certificado do evento ou do evento em si', null=True, verbose_name='URL do evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do projeto', max_length=100, verbose_name='Título')),
                ('document', models.FileField(blank=True, null=True, upload_to='documentos', verbose_name='Documentos')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Experience', verbose_name='Experiência')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('link', models.URLField(verbose_name='Link')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('about', models.TextField(blank=True, verbose_name='Sobre mim')),
                ('current_work', models.CharField(blank=True, default='Disponível', max_length=100, verbose_name='Trabalho Atual')),
                ('academic_formation', models.CharField(blank=True, max_length=100, verbose_name='Formação Academica')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='Curso')),
                ('languages', models.CharField(blank=True, max_length=100, verbose_name='Idiomas')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('position', models.CharField(help_text='Cargo ocupado no projeto', max_length=100, verbose_name='Cargo')),
                ('institution', models.CharField(help_text='Instituição que realizou ou contratou o projeto', max_length=100, verbose_name='Instituição')),
                ('start_date', models.DateField(verbose_name='Data de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de termino')),
                ('url', models.URLField(blank=True, help_text='URL do projeto', null=True, verbose_name='Link')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_voluntary', models.BooleanField(default=False, verbose_name='É voluntario?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('situation', models.CharField(choices=[('Concluido', 'Concluido'), ('Em Andamento', 'Em Andamento'), ('Parado', 'Parado'), ('Cancelado', 'Cancelado')], default='Em Andamento', help_text='Situação do projeto', max_length=100, verbose_name='Situação')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('level', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Nível')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('priority', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.Profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['priority', 'title', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='link',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.Profile', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.Profile', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.Profile', verbose_name='Perfil'),
        ),
    ]
