# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, verbose_name='Idade')),
                ('about', models.TextField(blank=True, verbose_name='Sobre mim')),
                ('current_work', models.CharField(blank=True, default='Disponível', max_length=100, verbose_name='Trabalho Atual')),
                ('academic_formation', models.CharField(blank=True, max_length=100, verbose_name='Formação Academica')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='Curso')),
                ('languages', models.CharField(blank=True, max_length=100, verbose_name='Idiomas')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Nível')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['title', 'level'],
            },
        ),
    ]
