# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Experience', verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Project', verbose_name='Projeto'),
        ),
    ]
