# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170212_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Victor Hugo', max_length=100, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Victor Hugo', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
