# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170212_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='short_title',
            field=models.CharField(blank=True, help_text='Abreveatura do título', max_length=100, verbose_name='Abreveatura'),
        ),
    ]
