# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experience_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='short_title',
            field=models.CharField(help_text='Abreveatura do título', max_length=100, verbose_name='Abreveatura'),
        ),
    ]
