# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170212_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Foto'),
        ),
    ]
