# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170212_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
