# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170212_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
