# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170212_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_formation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ensino Médio'),
        ),
    ]
