# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170213_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Outras', 'Outras'), ('Linguagem', 'Linguagem'), ('Devops', 'Devops'), ('Framework', 'Framework'), ('Design', 'Design'), ('Gestão', 'Gestão'), ('Negócios', 'Negócios')], default='Outras', max_length=100, verbose_name='Categoria'),
        ),
    ]
