# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.Certificate', verbose_name='Certificado')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.Skill', verbose_name='Habilidade'),
        ),
    ]
