# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170213_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='category',
            name='skill',
        ),
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('Linguagens', 'Linguagens'), ('Framework', 'Framework'), ('Design', 'Design'), ('Devops', 'Devops'), ('Governança de TI', 'Governança de TI'), ('Outras', 'Outras')], default='Outras', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Linguagens', 'Linguagens'), ('Framework', 'Framework'), ('Design', 'Design'), ('Devops', 'Devops'), ('Governança de TI', 'Governança de TI'), ('Outras', 'Outras')], default='Outras', max_length=100, verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
