# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170213_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['title', 'issuing_institution', 'category', 'created_at'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['priority', 'title', 'category', 'created_at'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='has_expired_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='license_number',
        ),
        migrations.AddField(
            model_name='link',
            name='fa_icon',
            field=models.CharField(blank=True, help_text='Inserir os icones do font awesome em http://fontawesome.io/ ou http://www.w3schools.com/icons/fontawesome_icons_intro.asp', max_length=100, verbose_name='Icone Font Awesome'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.ImageField(default=1, upload_to='documentos', verbose_name='Arquivo do certificado'),
            preserve_default=False,
        ),
    ]
