# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170214_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
    ]
