# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_link_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Área de Interesse')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('fa_icon', models.CharField(blank=True, help_text='Inserir os icones do font awesome em http://fontawesome.io/ ou http://www.w3schools.com/icons/fontawesome_icons_intro.asp', max_length=100, verbose_name='Icone Font Awesome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.Profile', verbose_name='Perfil')),
            ],
        ),
    ]
