# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_interest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['title'], 'verbose_name': 'Área de Interesse', 'verbose_name_plural': 'Áreas de interesse'},
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tags'),
        ),
    ]
