# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Framework', 'Framework'), ('Design', 'Design'), ('Devops', 'Devops'), ('Management', 'Management and Business'), ('Others', 'Others')], default='Others', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='situation',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Stopped', 'Stopped'), ('Canceled', 'Canceled')], default='In progress', help_text='Situação do projeto', max_length=100, verbose_name='Situação'),
        ),
    ]
