# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170216_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.URLField(help_text='URL do google driver do certificado para o iframe', verbose_name='URL do certificado'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='url',
            field=models.URLField(blank=True, help_text='URL official do certificado', null=True, verbose_name='URL do certificado'),
        ),
    ]
