# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170216_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.ImageField(upload_to='certificates', verbose_name='Certificados'),
        ),
    ]
